services:
  postgres:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: ask_dmc
      POSTGRES_USER: ask_dmc
      POSTGRES_PASSWORD: ask_dmc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  pgdata:
